import React, { useState, useEffect, useRef } from 'react';
import { 
  Sparkles, 
  Upload, 
  FileText, 
  BookOpen, 
  Bookmark, 
  Copy, 
  Download, 
  RotateCcw, 
  Sliders, 
  Zap, 
  Volume2, 
  VolumeX, 
  History, 
  Trash2, 
  Check, 
  ArrowRight,
  ListTodo,
  AlertCircle,
  Clock,
  Save
} from 'lucide-react';
import { Button } from '../components/common/Button';
import { 
  generateAISummary, 
  SAMPLE_NOTES, 
  readFileAsText, 
  getSummaryHistory, 
  deleteSummaryFromHistory 
} from '../services/summaryService';
import type { AISummaryResult, SummaryOptions, SampleNote } from '../types/summary';

export const SummaryPage: React.FC = () => {
  const [inputText, setInputText] = useState<string>('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [summaryResult, setSummaryResult] = useState<AISummaryResult | null>(null);
  const [activeTab, setActiveTab] = useState<'short' | 'detailed' | 'keyPoints' | 'definitions' | 'actionItems'>('short');
  
  // Customization Options
  const [options, setOptions] = useState<SummaryOptions>({
    length: 'standard',
    tone: 'academic',
    customFocus: ''
  });
  const [showOptionsModal, setShowOptionsModal] = useState<boolean>(false);
  
  // Audio state
  const [isSpeaking, setIsSpeaking] = useState<boolean>(false);
  
  // Copy state
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [savedToNotesMsg, setSavedToNotesMsg] = useState<boolean>(false);
  
  // History state
  const [history, setHistory] = useState<AISummaryResult[]>([]);
  const [showHistoryDrawer, setShowHistoryDrawer] = useState<boolean>(false);

  // Drag & drop state
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setHistory(getSummaryHistory());
  }, []);

  const handleFileUpload = async (file: File) => {
    setSelectedFile(file);
    setErrorMessage(null);
    try {
      if (file.name.endsWith('.txt') || file.name.endsWith('.md') || file.name.endsWith('.json') || file.name.endsWith('.csv')) {
        const text = await readFileAsText(file);
        setInputText(text);
      } else {
        // Simple fallback note text for unreadable binary files (e.g. PDF demo)
        setInputText(`Document Content (${file.name}):\n\nNotes uploaded from ${file.name}. Click 'Generate AI Summary' to process the full summary breakdown, extract key definitions, key takeaways, and action items.`);
      }
    } catch (err) {
      setErrorMessage('Failed to read file content. Please paste text directly.');
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileUpload(e.dataTransfer.files[0]);
    }
  };

  const handleSelectSample = (sample: SampleNote) => {
    setInputText(sample.content);
    setSelectedFile(null);
    setErrorMessage(null);
  };

  const handleGenerate = async () => {
    if (!inputText.trim()) {
      setErrorMessage('Please enter or upload study notes first.');
      return;
    }

    setIsGenerating(true);
    setErrorMessage(null);
    
    try {
      const result = await generateAISummary(inputText, options);
      setSummaryResult(result);
      setActiveTab('short');
      setHistory(getSummaryHistory());
    } catch (err: any) {
      setErrorMessage(err.message || 'Failed to generate summary. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleToggleActionItem = (itemId: string) => {
    if (!summaryResult) return;
    const updated = {
      ...summaryResult,
      actionItems: summaryResult.actionItems.map(item =>
        item.id === itemId ? { ...item, completed: !item.completed } : item
      )
    };
    setSummaryResult(updated);
  };

  const handleCopyText = (text: string, sectionName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionName);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleDownloadReport = () => {
    if (!summaryResult) return;
    
    const reportText = `# ${summaryResult.title} - AI Summary Report
Generated by StudyGenie AI on ${summaryResult.metadata.createdAt}

## ⚡ SHORT SUMMARY
${summaryResult.shortSummary}

## 📖 DETAILED SUMMARY
${summaryResult.detailedSummary}

## 📌 KEY POINTS
${summaryResult.keyPoints.map(kp => `- **${kp.title}**: ${kp.description}`).join('\n')}

## 📘 IMPORTANT DEFINITIONS
${summaryResult.importantDefinitions.map(def => `- **${def.term}**: ${def.definition} ${def.context ? `(${def.context})` : ''}`).join('\n')}

## ✅ ACTION ITEMS
${summaryResult.actionItems.map(act => `- [${act.completed ? 'x' : ' '}] ${act.task}`).join('\n')}
`;

    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${summaryResult.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_summary.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleToggleSpeech = () => {
    if (!summaryResult) return;
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      const textToRead = activeTab === 'short' ? summaryResult.shortSummary : summaryResult.detailedSummary;
      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  const handleSaveToNotes = () => {
    if (!summaryResult) return;
    try {
      const existing = localStorage.getItem('studygenie_saved_notes');
      const notes = existing ? JSON.parse(existing) : [];
      const newNote = {
        id: `note_${Date.now()}`,
        title: summaryResult.title,
        content: summaryResult.detailedSummary,
        aiSummary: summaryResult.shortSummary,
        date: summaryResult.metadata.createdAt,
        tags: ['AI Summary', options.tone]
      };
      localStorage.setItem('studygenie_saved_notes', JSON.stringify([newNote, ...notes]));
      setSavedToNotesMsg(true);
      setTimeout(() => setSavedToNotesMsg(false), 3000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleDeleteHistory = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = deleteSummaryFromHistory(id);
    setHistory(updated);
    if (summaryResult?.id === id) {
      setSummaryResult(null);
    }
  };

  const wordCount = inputText.trim() ? inputText.trim().split(/\s+/).length : 0;
  const estimatedReadTime = Math.max(1, Math.ceil(wordCount / 200));

  return (
    <div className="space-y-8 animate-fadeIn max-w-7xl mx-auto pb-12">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center space-x-2">
            <span className="px-2.5 py-0.5 rounded-full bg-gradient-to-r from-indigo-500/10 to-purple-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20 text-xs font-bold uppercase tracking-wider flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              AI Intelligence Suite
            </span>
          </div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-slate-100 mt-2 flex items-center gap-3">
            AI Notes Summarizer
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
            Transform lengthy lecture notes, articles, and documents into instant structured summaries, key definitions, and action items.
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <Button
            onClick={() => setShowHistoryDrawer(true)}
            variant="secondary"
            className="px-3.5 py-2 text-xs font-medium rounded-xl border border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center space-x-2 shadow-sm"
          >
            <History className="w-4 h-4 text-indigo-500" />
            <span>History ({history.length})</span>
          </Button>

          <Button
            onClick={() => setShowOptionsModal(true)}
            variant="secondary"
            className="px-3.5 py-2 text-xs font-medium rounded-xl border border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 flex items-center space-x-2 shadow-sm"
          >
            <Sliders className="w-4 h-4 text-purple-500" />
            <span>Options</span>
          </Button>
        </div>
      </div>

      {/* Main Grid: Left Upload/Input Panel, Right Output Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Input & Controls (5 Cols) */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* Sample Preset Selector */}
          <div className="bg-white/70 dark:bg-slate-900/80 p-4 rounded-3xl border border-slate-200 dark:border-slate-800 backdrop-blur-xl space-y-3 shadow-lg">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
                <BookOpen className="w-4 h-4 text-indigo-500" />
                Quick Sample Notes
              </span>
              <span className="text-[10px] text-slate-400">Click to test</span>
            </div>
            <div className="grid grid-cols-1 gap-2">
              {SAMPLE_NOTES.map((sample) => (
                <button
                  key={sample.id}
                  onClick={() => handleSelectSample(sample)}
                  className="p-2.5 rounded-2xl bg-slate-100/70 dark:bg-slate-800/50 hover:bg-indigo-50 dark:hover:bg-indigo-950/40 border border-slate-200/60 dark:border-slate-700/50 hover:border-indigo-500/40 text-left transition-all group flex items-center justify-between"
                >
                  <div>
                    <p className="text-xs font-bold text-slate-800 dark:text-slate-200 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 truncate">
                      {sample.title}
                    </p>
                    <p className="text-[10px] text-slate-400">{sample.category}</p>
                  </div>
                  <ArrowRight className="w-3.5 h-3.5 text-slate-400 group-hover:text-indigo-500 group-hover:translate-x-0.5 transition-all flex-shrink-0" />
                </button>
              ))}
            </div>
          </div>

          {/* Upload & Text Input Card */}
          <div className="bg-white/70 dark:bg-slate-900/80 p-5 rounded-3xl border border-slate-200 dark:border-slate-800 backdrop-blur-xl shadow-lg space-y-4">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <FileText className="w-4 h-4 text-indigo-500" />
                Upload File or Paste Notes
              </label>
              {inputText && (
                <button
                  onClick={() => { setInputText(''); setSelectedFile(null); }}
                  className="text-[11px] text-slate-400 hover:text-rose-500 transition-colors flex items-center gap-1"
                >
                  <RotateCcw className="w-3 h-3" />
                  Clear
                </button>
              )}
            </div>

            {/* Drag and Drop Zone */}
            <div
              onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`
                p-4 border-2 border-dashed rounded-2xl transition-all cursor-pointer flex flex-col items-center justify-center text-center space-y-2
                ${isDragging 
                  ? 'border-indigo-500 bg-indigo-500/10' 
                  : 'border-slate-300 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30 hover:border-indigo-400 hover:bg-slate-100/50 dark:hover:bg-slate-800/50'}
              `}
            >
              <input
                type="file"
                ref={fileInputRef}
                onChange={(e) => e.target.files?.[0] && handleFileUpload(e.target.files[0])}
                accept=".txt,.md,.json,.pdf,.docx"
                className="hidden"
              />
              <div className="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-500 flex items-center justify-center">
                <Upload className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                  {selectedFile ? selectedFile.name : 'Drop file here or click to browse'}
                </p>
                <p className="text-[10px] text-slate-400 mt-0.5">
                  Supports .TXT, .MD, .PDF, .DOCX, .JSON notes
                </p>
              </div>
            </div>

            {/* Textarea */}
            <div className="relative">
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Paste your raw notes, study guides, or document content here..."
                rows={10}
                className="w-full p-4 rounded-2xl text-xs bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 border border-slate-200 dark:border-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 leading-relaxed font-sans resize-none"
              />
              
              <div className="flex items-center justify-between mt-2 px-1 text-[11px] text-slate-400">
                <span className="flex items-center gap-2">
                  <Clock className="w-3 h-3 text-indigo-400" />
                  {wordCount} words (~{estimatedReadTime} min read)
                </span>
                <span>{inputText.length} characters</span>
              </div>
            </div>

            {/* Error Message */}
            {errorMessage && (
              <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-xs flex items-center gap-2">
                <AlertCircle className="w-4 h-4 flex-shrink-0" />
                <span>{errorMessage}</span>
              </div>
            )}

            {/* Generate Action Button */}
            <Button
              onClick={handleGenerate}
              disabled={isGenerating || !inputText.trim()}
              className="w-full py-3 text-xs font-bold rounded-2xl bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:from-indigo-500 hover:to-pink-500 text-white shadow-lg shadow-indigo-500/25 transition-all flex items-center justify-center space-x-2 disabled:opacity-50"
            >
              {isGenerating ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>AI Analyzing & Summarizing...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 animate-pulse" />
                  <span>Generate AI Summary</span>
                </>
              )}
            </Button>

          </div>
        </div>

        {/* Right Column: Output Summary Display (7 Cols) */}
        <div className="lg:col-span-7 space-y-6">
          {summaryResult ? (
            <div className="bg-white/70 dark:bg-slate-900/80 rounded-3xl border border-slate-200 dark:border-slate-800 backdrop-blur-xl shadow-xl overflow-hidden flex flex-col min-h-[580px]">
              
              {/* Header Title Bar */}
              <div className="p-6 border-b border-slate-200 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-950/40 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <div className="flex items-center space-x-2">
                    <span className="px-2.5 py-0.5 rounded-md bg-indigo-500/10 text-indigo-500 text-[10px] font-bold uppercase border border-indigo-500/20">
                      AI Generated
                    </span>
                    <span className="text-[11px] text-slate-400">{summaryResult.metadata.createdAt}</span>
                  </div>
                  <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 mt-1 leading-snug">
                    {summaryResult.title}
                  </h2>
                </div>

                {/* Toolbar buttons */}
                <div className="flex items-center space-x-2 flex-shrink-0">
                  <button
                    onClick={handleToggleSpeech}
                    title={isSpeaking ? "Stop Reading" : "Read Aloud"}
                    className={`p-2 rounded-xl border text-xs transition-colors ${
                      isSpeaking
                        ? 'bg-rose-500 text-white border-rose-500'
                        : 'bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:text-indigo-500'
                    }`}
                  >
                    {isSpeaking ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
                  </button>

                  <button
                    onClick={() => handleCopyText(
                      activeTab === 'short' 
                        ? summaryResult.shortSummary 
                        : summaryResult.detailedSummary, 
                      activeTab
                    )}
                    title="Copy Text"
                    className="p-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:text-indigo-500 transition-colors flex items-center space-x-1"
                  >
                    {copiedSection === activeTab ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                  </button>

                  <button
                    onClick={handleSaveToNotes}
                    title="Save to Notes"
                    className="p-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:text-indigo-500 transition-colors flex items-center space-x-1"
                  >
                    {savedToNotesMsg ? <Check className="w-4 h-4 text-emerald-500" /> : <Save className="w-4 h-4" />}
                  </button>

                  <button
                    onClick={handleDownloadReport}
                    title="Download Report"
                    className="p-2 rounded-xl border border-indigo-500/30 bg-indigo-600 text-white hover:bg-indigo-500 transition-colors shadow-sm"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Navigation Tabs (5 Requested Sections) */}
              <div className="flex items-center overflow-x-auto px-4 pt-3 border-b border-slate-200 dark:border-slate-800 gap-1 scrollbar-none bg-slate-100/40 dark:bg-slate-900/40">
                <button
                  onClick={() => setActiveTab('short')}
                  className={`px-3.5 py-2.5 text-xs font-semibold rounded-t-xl transition-all flex items-center space-x-2 border-b-2 whitespace-nowrap ${
                    activeTab === 'short'
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-900'
                      : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                >
                  <Zap className="w-3.5 h-3.5 text-amber-500" />
                  <span>Short Summary</span>
                </button>

                <button
                  onClick={() => setActiveTab('detailed')}
                  className={`px-3.5 py-2.5 text-xs font-semibold rounded-t-xl transition-all flex items-center space-x-2 border-b-2 whitespace-nowrap ${
                    activeTab === 'detailed'
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-900'
                      : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                >
                  <FileText className="w-3.5 h-3.5 text-indigo-500" />
                  <span>Detailed Summary</span>
                </button>

                <button
                  onClick={() => setActiveTab('keyPoints')}
                  className={`px-3.5 py-2.5 text-xs font-semibold rounded-t-xl transition-all flex items-center space-x-2 border-b-2 whitespace-nowrap ${
                    activeTab === 'keyPoints'
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-900'
                      : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                >
                  <Bookmark className="w-3.5 h-3.5 text-purple-500" />
                  <span>Key Points ({summaryResult.keyPoints.length})</span>
                </button>

                <button
                  onClick={() => setActiveTab('definitions')}
                  className={`px-3.5 py-2.5 text-xs font-semibold rounded-t-xl transition-all flex items-center space-x-2 border-b-2 whitespace-nowrap ${
                    activeTab === 'definitions'
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-900'
                      : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                >
                  <BookOpen className="w-3.5 h-3.5 text-cyan-500" />
                  <span>Definitions ({summaryResult.importantDefinitions.length})</span>
                </button>

                <button
                  onClick={() => setActiveTab('actionItems')}
                  className={`px-3.5 py-2.5 text-xs font-semibold rounded-t-xl transition-all flex items-center space-x-2 border-b-2 whitespace-nowrap ${
                    activeTab === 'actionItems'
                      ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400 bg-white dark:bg-slate-900'
                      : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
                  }`}
                >
                  <ListTodo className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Action Items ({summaryResult.actionItems.length})</span>
                </button>
              </div>

              {/* Tab Content Display */}
              <div className="p-6 flex-1 overflow-y-auto max-h-[600px]">
                
                {/* 1. Short Summary Tab */}
                {activeTab === 'short' && (
                  <div className="space-y-6 animate-fadeIn">
                    <div className="p-5 rounded-2xl bg-gradient-to-r from-indigo-500/10 via-purple-500/10 to-pink-500/10 border border-indigo-500/20 text-slate-800 dark:text-slate-200 space-y-3">
                      <div className="flex items-center space-x-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs">
                        <Zap className="w-4 h-4 fill-indigo-500/20" />
                        <span>EXECUTIVE TL;DR OVERVIEW</span>
                      </div>
                      <p className="text-sm leading-relaxed font-medium">
                        {summaryResult.shortSummary}
                      </p>
                    </div>

                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-2">
                      <div className="p-3.5 rounded-xl bg-slate-100/70 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 text-center">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Words Analyzed</p>
                        <p className="text-lg font-extrabold text-indigo-500 mt-0.5">{summaryResult.metadata.wordCount}</p>
                      </div>
                      <div className="p-3.5 rounded-xl bg-slate-100/70 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 text-center">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Key Points</p>
                        <p className="text-lg font-extrabold text-purple-500 mt-0.5">{summaryResult.keyPoints.length}</p>
                      </div>
                      <div className="p-3.5 rounded-xl bg-slate-100/70 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 text-center col-span-2 sm:col-span-1">
                        <p className="text-[10px] uppercase font-bold text-slate-400">Action Tasks</p>
                        <p className="text-lg font-extrabold text-emerald-500 mt-0.5">{summaryResult.actionItems.length}</p>
                      </div>
                    </div>
                  </div>
                )}

                {/* 2. Detailed Summary Tab */}
                {activeTab === 'detailed' && (
                  <div className="space-y-4 animate-fadeIn text-slate-700 dark:text-slate-300 text-xs sm:text-sm leading-relaxed whitespace-pre-line font-sans">
                    <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs">
                      {summaryResult.detailedSummary}
                    </div>
                  </div>
                )}

                {/* 3. Key Points Tab */}
                {activeTab === 'keyPoints' && (
                  <div className="space-y-4 animate-fadeIn">
                    <p className="text-xs text-slate-500 dark:text-slate-400">Core takeaways and primary arguments extracted from the document:</p>
                    <div className="space-y-3">
                      {summaryResult.keyPoints.map((kp, idx) => (
                        <div 
                          key={kp.id || idx}
                          className="p-4 rounded-2xl bg-slate-50/80 dark:bg-slate-800/40 border border-slate-200/80 dark:border-slate-700/60 hover:border-indigo-500/40 transition-all flex items-start space-x-3.5"
                        >
                          <div className="w-7 h-7 rounded-xl bg-indigo-500/10 text-indigo-500 font-extrabold text-xs flex items-center justify-center flex-shrink-0 mt-0.5">
                            {idx + 1}
                          </div>
                          <div className="flex-1">
                            <div className="flex items-center justify-between">
                              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">{kp.title}</h4>
                              {kp.priority && (
                                <span className={`text-[9px] font-extrabold uppercase px-2 py-0.5 rounded-full border ${
                                  kp.priority === 'high' 
                                    ? 'bg-rose-500/10 text-rose-500 border-rose-500/20' 
                                    : 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20'
                                }`}>
                                  {kp.priority} Priority
                                </span>
                              )}
                            </div>
                            <p className="text-xs text-slate-600 dark:text-slate-300 mt-1 leading-relaxed">{kp.description}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* 4. Important Definitions Tab */}
                {activeTab === 'definitions' && (
                  <div className="space-y-4 animate-fadeIn">
                    <p className="text-xs text-slate-500 dark:text-slate-400">Key terminology, concepts, and vocabulary defined in the material:</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      {summaryResult.importantDefinitions.map((def, idx) => (
                        <div
                          key={def.id || idx}
                          className="p-4 rounded-2xl bg-slate-50/80 dark:bg-slate-800/40 border border-slate-200/80 dark:border-slate-700/60 space-y-2"
                        >
                          <div className="flex items-center space-x-2">
                            <BookOpen className="w-4 h-4 text-cyan-500" />
                            <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">{def.term}</h4>
                          </div>
                          <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed font-medium">{def.definition}</p>
                          {def.context && (
                            <p className="text-[11px] text-slate-400 italic pt-1 border-t border-slate-200/40 dark:border-slate-700/40">
                              Context: {def.context}
                            </p>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* 5. Action Items Tab */}
                {activeTab === 'actionItems' && (
                  <div className="space-y-4 animate-fadeIn">
                    <p className="text-xs text-slate-500 dark:text-slate-400">Recommended next steps, study actions, and review items derived from notes:</p>
                    <div className="space-y-2.5">
                      {summaryResult.actionItems.map((act) => (
                        <div
                          key={act.id}
                          onClick={() => handleToggleActionItem(act.id)}
                          className={`p-3.5 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                            act.completed
                              ? 'bg-emerald-500/5 dark:bg-emerald-950/20 border-emerald-500/30 text-slate-400 line-through'
                              : 'bg-slate-50/80 dark:bg-slate-800/40 border-slate-200/80 dark:border-slate-700/60 text-slate-800 dark:text-slate-200 hover:border-indigo-500/40'
                          }`}
                        >
                          <div className="flex items-center space-x-3">
                            <div className={`w-5 h-5 rounded-lg border flex items-center justify-center transition-colors ${
                              act.completed 
                                ? 'bg-emerald-500 border-emerald-500 text-white' 
                                : 'border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900'
                            }`}>
                              {act.completed && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                            </div>
                            <span className="text-xs font-medium">{act.task}</span>
                          </div>
                          {act.priority && (
                            <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-200/60 dark:bg-slate-700/60 text-slate-500 dark:text-slate-400 font-semibold">
                              {act.priority}
                            </span>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

              </div>
            </div>
          ) : (
            // Placeholder empty state before generation
            <div className="h-full min-h-[550px] rounded-3xl border-2 border-dashed border-slate-200 dark:border-slate-800 flex flex-col items-center justify-center p-8 text-center bg-white/40 dark:bg-slate-900/40 backdrop-blur-sm space-y-4">
              <div className="w-16 h-16 rounded-3xl bg-gradient-to-tr from-indigo-500/20 via-purple-500/20 to-pink-500/20 text-indigo-500 flex items-center justify-center shadow-inner">
                <Sparkles className="w-8 h-8 animate-pulse text-indigo-500" />
              </div>
              <div className="max-w-md space-y-2">
                <h3 className="text-lg font-bold text-slate-800 dark:text-slate-200">
                  Ready to Summarize Your Notes
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                  Paste your study notes or select a sample note on the left, then click <strong>Generate AI Summary</strong> to view your Short Summary, Detailed Breakdown, Key Points, Important Definitions, and Action Items!
                </p>
              </div>
            </div>
          )}
        </div>

      </div>

      {/* History Drawer Modal */}
      {showHistoryDrawer && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex justify-end">
          <div className="w-full max-w-md bg-white dark:bg-slate-900 h-full p-6 space-y-6 flex flex-col border-l border-slate-200 dark:border-slate-800 shadow-2xl animate-slideLeft">
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
              <div className="flex items-center space-x-2">
                <History className="w-5 h-5 text-indigo-500" />
                <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">Summary History</h3>
              </div>
              <button 
                onClick={() => setShowHistoryDrawer(false)}
                className="text-slate-400 hover:text-slate-200 text-xs font-bold px-2 py-1 rounded-lg bg-slate-100 dark:bg-slate-800"
              >
                Close
              </button>
            </div>

            <div className="flex-1 overflow-y-auto space-y-3">
              {history.length === 0 ? (
                <p className="text-xs text-slate-400 text-center py-12">No saved summary history found.</p>
              ) : (
                history.map((item) => (
                  <div
                    key={item.id}
                    onClick={() => { setSummaryResult(item); setShowHistoryDrawer(false); }}
                    className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700/60 hover:border-indigo-500/40 cursor-pointer transition-all space-y-2 group"
                  >
                    <div className="flex items-center justify-between">
                      <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100 group-hover:text-indigo-500 truncate max-w-[240px]">
                        {item.title}
                      </h4>
                      <button
                        onClick={(e) => handleDeleteHistory(item.id, e)}
                        className="text-slate-400 hover:text-rose-500 p-1 rounded-md"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                    <p className="text-[11px] text-slate-500 dark:text-slate-400 line-clamp-2">{item.shortSummary}</p>
                    <div className="flex items-center justify-between text-[10px] text-slate-400 pt-1 border-t border-slate-200/50 dark:border-slate-700/50">
                      <span>{item.metadata.createdAt}</span>
                      <span>{item.keyPoints.length} points • {item.actionItems.length} tasks</span>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* Options Modal */}
      {showOptionsModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-white dark:bg-slate-900 rounded-3xl p-6 space-y-5 border border-slate-200 dark:border-slate-800 shadow-2xl animate-scaleUp">
            <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
              <h3 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <Sliders className="w-4 h-4 text-purple-500" />
                Summary Generator Options
              </h3>
              <button 
                onClick={() => setShowOptionsModal(false)}
                className="text-slate-400 hover:text-slate-200 text-xs font-bold"
              >
                ✕
              </button>
            </div>

            {/* Length option */}
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Summary Length</label>
              <div className="grid grid-cols-3 gap-2">
                {(['concise', 'standard', 'comprehensive'] as const).map((len) => (
                  <button
                    key={len}
                    onClick={() => setOptions({ ...options, length: len })}
                    className={`py-2 rounded-xl text-xs font-semibold capitalize border transition-all ${
                      options.length === len
                        ? 'bg-indigo-600 text-white border-indigo-600'
                        : 'bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300'
                    }`}
                  >
                    {len}
                  </button>
                ))}
              </div>
            </div>

            {/* Tone option */}
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Academic Tone / Audience</label>
              <div className="grid grid-cols-2 gap-2">
                {(['academic', 'simplified', 'executive', 'exam-focused'] as const).map((tone) => (
                  <button
                    key={tone}
                    onClick={() => setOptions({ ...options, tone: tone })}
                    className={`py-2 rounded-xl text-xs font-semibold capitalize border transition-all ${
                      options.tone === tone
                        ? 'bg-purple-600 text-white border-purple-600'
                        : 'bg-slate-100 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300'
                    }`}
                  >
                    {tone}
                  </button>
                ))}
              </div>
            </div>

            {/* Custom focus input */}
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Custom Focus / Topics to Emphasize</label>
              <input
                type="text"
                placeholder="e.g. Focus on formulas, key dates, or algorithms..."
                value={options.customFocus || ''}
                onChange={(e) => setOptions({ ...options, customFocus: e.target.value })}
                className="w-full p-3 rounded-xl text-xs bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-slate-100 border border-slate-200 dark:border-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>

            <Button
              onClick={() => setShowOptionsModal(false)}
              className="w-full py-2.5 text-xs font-bold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white"
            >
              Save Preferences
            </Button>
          </div>
        </div>
      )}

    </div>
  );
};
